#!/bin/zsh

# Find the brew command
local brewcmds=()
for candidate in \
  "$HOME/.homebrew/bin/brew" \
  "$HOME/.linuxbrew/bin/brew" \
  "/opt/homebrew/bin/brew" \
  "/usr/local/bin/brew"
do
  [[ -x "$candidate" ]] && brewcmds+=("$candidate")
done

if (( ${#brewcmds[@]} == 0 )); then
  echo >&2 "brew command not found. Install from https://brew.sh"
  return 1
fi

eval "$("${brewcmds[1]}" shellenv)"
